name: mindfulness_with_nature_app_flutter
description: A mindfulness app with nature themes

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.5.3
  google_maps_flutter: ^2.14.0
  fl_chart: ^0.67.0 
  uuid: ^4.5.2
  intl: ^0.20.2
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.2
  cloud_firestore: ^4.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true